import type { NextPage } from 'next'
import React, { useRef, useState, useEffect } from 'react'; 
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@components/Button';
import { css } from '@emotion/react';

const Home: NextPage = () => {
  // useState 타입 정의
  // const [products, setProducts] = useState<{ id: string; properties: { id: string }[] }[]>([]);

  const [products, setProducts] = useState<{ id: string; name: string; createdAt: string }[]>([]);

  // useEffect(() => {
  //   fetch('/api/get-items').then(res => res.json())
  //     .then(data => setProducts(data.items));
  // }, []);
  
  useEffect(() => {
    fetch('/api/get-products').then(res => res.json())
      .then(data => setProducts(data.items));
  }, []);

  const inputRef = useRef<HTMLInputElement>(null);
  const handleClick = () => {
    if (inputRef.current == null || inputRef.current.value === '') {
      alert('name을 넣어주세요.');
      return;
    }
    fetch(`/api/add-item?name=${inputRef.current.value}`)
      .then(res => res.json())
      .then(data => {
        alert(data.message);
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <input className="mt-2 p-3 w-96 focus:border-red-500 focus:outline-none peer-invalid:visible text-pink-600 text-sm" type="text" ref={ inputRef } placeholder="name"/>
        
        <button
          css={css`
            background-color: hotpink;
            padding: 16px;
            border-radius: 8px;
          `}
          onClick={handleClick}>Add Jacket</button>
        
        <Button onClick={handleClick}>Add Jacket2</Button>

        <div>
          <p>Produt List</p>
          {products && products.map((item) => {
            return(
              <div key={item.id}>{item.name}<span>{ item.createdAt}</span></div>
            )
          })}
          {/* {
            products && products.map((item) => {
              return (
              <div key={item.id}>
                {JSON.stringify(item)}
                {item.properties &&
                    Object.entries(item.properties).map(([key, value]) => {
                    return(
                    // 버튼을 누르면 디테일 조회
                    <button key = { key } onClick = {() => {
                      fetch(`/api/get-detail?pageId=${item.id}&propertyId=${value.id}`)
                        .then(res => res.json())
                        .then((data) => alert(JSON.stringify(data.detail)))
                        }}> {key}</button>
                    )
                  })}
                  <br/><br/>
                </div>  
              )
            })
          } */}
        </div>
      </main>

      <footer className={styles.footer}> 
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
